### ISSUE TITLE
C/C++ implementation of blocked matrix multiply has a typo

### ISSUE THREAD

**Issue by barrbrain** [SamsungInternet/wasm-js-perf#1]
https://github.com/SamsungInternet/wasm-js-perf/blob/b3f75039e2e01d8c7240282d11e3354d53ba5412/mmm.cpp#L17

This should be a simple assignment, accumulation occurs in the loop above.

**Comment by winstonchen** [comment]
You are correct. I updated the file and regenerated the wasm file.

https://github.com/SamsungInternet/wasm-js-perf/commit/d4146eaa8840125bc98050500fcdcbd8d8b36ed1

Thanks for discovering this.
